# Generated by Django 3.1.7 on 2022-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('country_name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=250)),
                ('content', models.TextField(default='')),
                ('image_url', models.CharField(default='', max_length=200)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
